### ISSUE TITLE
ElementsCollection.size() wrong value

### ISSUE THREAD

**Issue by Maratori** [codeborne/selenide#643] opened 2017-12-10 18:17 UTC
## The problem
We have an ElementsCollection instance.
Let's call `elementsCollection.size()`. Then add new html element.
Call again `elementsCollection.size()`. It returns the same value as the first time.
It's a bug, I think.

## Details
That happens because method `ElementsCollection.getActualElements()` calls `collection.getActualElements()` just once.

## Tell us about your environment
* **Selenide Version: 4.8**

## Code To Reproduce Issue
```java
class ElementsCollectionSizeTest {
    @Test
    void elementsCollectionSizeTest() {
        Configuration.browser = "chrome";
        open("http://selenide.org/");
        SelenideElement container = $(".main-menu-pages");
        ElementsCollection collection = container.$$("li");
        assertEquals(7, collection.size());
        executeJavaScript("arguments[0].appendChild(document.createElement('li'));", container);
        assertEquals(8, container.$$("li").size());
        assertEquals(7, collection.size()); // <- doesn't fail here
        assertEquals(8, collection.size()); // <- unexpected fail here
    }
}
```

**Comment by danteg233** [comment] 2017-12-11 08:30
@Maratori Hi man, it's a famous let's say case with Selenide. [Here](https://github.com/codeborne/selenide/issues/181) u can read for your understanding. Yep it's been 2 years since opening issue, but still hasn't been resolved yet.
Well, we solved this through creating our own Collection, and by adding method `Refresh`. That method simply refreshes collection.

**Comment by BorisOsipov** [comment] 2017-12-11 08:32
@danteg233 thanks for referencing.

@Maratori closed as duplicate of https://github.com/codeborne/selenide/issues/181

**Closed by BorisOsipov** 2017-12-11 08:32 UTC
