### ISSUE TITLE
The main window is not sometimes captured in screenshot, but the popup window is captured.

### ISSUE THREAD

**Issue by anyone-can-test** [codeborne/selenide#455] opened 2017-01-18 00:44 UTC
I posted a issue to chrome driver.
https://groups.google.com/forum/#!topic/chromedriver-users/fJBD8vBJ6Jo

```
Screenshot is generated on every failed tests.
In chrome driver 2.22 + chrome 51, there is no problem.
But after updating chrome driver 2.27 + chrome 55, 
screenshot is sometimes wrong.

There are a main windows and a popup window.
In chrome driver 2.22, always the main windows is captured in screenshots.
In chrome driver 2.27, sometimes the popup window is captured in screenshot.
The screenshot (image file) is the popup window, but the html file is the main window.
```

Is there any relation to Selenide?

**Comment by asolntsev** [comment] 2017-03-16 22:42
@anyone-can-test No, I don't believe that it's caused by some Selenide change. But thanks for reporting. Did you get some feedback from chromedriver developers?

**Comment by anyone-can-test** [comment] 2017-03-17 06:48
@asolntsev 

no feedback from chromedriver.
Maybe it's related to the recent chromedriver.

**Comment by asolntsev** [comment] 2017-03-17 08:47
Ok, I am closing the issue for now. Feel free to reopen it if new information comes.

**Closed by asolntsev** 2017-03-17 08:47 UTC
Labels: not a bug
