### ISSUE TITLE
$$("...").get(...) runs the search of the element

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#184] opened 2015-06-10 16:12 UTC
The design should be that only .should..() fires the actual search of the element on the page, thus preventing many of the StaleElementException cases.

But $$("...").get (and probably others, like find(), filter() etc. as well) seems to start searching actions.

Example:

https://gist.github.com/vinogradoff/e1d7570da4e18a7a6797

The both WebElements are semantically the same (first of the class list), but firstListElement doesn't start searching, whereas firstListElement2 - does. In my case with 2.18.2 is started the Firefox instead of Chrome when executing the initialization.

**Comment by asolntsev** [comment] 2015-06-13 07:59
I could only reproduce the problem in DEBUG mode (when I set breakpoint in method `setup`).
I cannot reproduce the problem in RUN mode. For me, both `$` and `$$` run Chrome. 

The cause of the problem it quite tricky. When test execution stops at a breakpoint, IDEA automatically calls `toString()` method on all local variables. This `toString()` causes Selenide to open browser and fetch web elements.

**Comment by vinogradoff** [comment] 2015-07-01 23:03
Same for me with 2.19... Can be put on hold or closed for the time being. I'll reopen it reproduction is found

**Comment by asolntsev** [comment] 2015-07-02 06:47
ok, good. Closing the issue.

**Closed by asolntsev** 2015-07-02 06:47 UTC
Labels: cannot preproduce
