### ISSUE TITLE
PhantomJS fails with Selenide v 4.4.1

### ISSUE THREAD

**Issue by SergeyPirogov** [codeborne/selenide#507] opened 2017-03-29 12:25 UTC
Tried to run PhantomJS with Selenide 4.4.1.

 Fail 
```
java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access class org.openqa.selenium.os.ExecutableFinder from class org.openqa.selenium.phantomjs.PhantomJSDriverService
```
Used gradle

**Comment by rmarinsky** [comment] 2017-03-29 12:37
Have you installed PhantomJS on your machine?

**Comment by SergeyPirogov** [comment] 2017-03-29 12:37
If you mean binary path - yes

**Comment by rmarinsky** [comment] 2017-03-29 12:56
Strange, i don't have such an error. 
My Steps:
1. Download bin from http://phantomjs.org/download.html
2. Update selenide to 4.4.1 in gradle dpendencies
3. Add phatnomjs to windows system variables 
4: ```@Rule
    public TextReport textReport = new TextReport();

    static {
        Configuration.browser = WebDriverRunner.PHANTOMJS;
        PhantomJsDriverManager.getInstance().setup();
    }

    @Test
    public void Test(){
        open("https://gd.tickets.ua/");
        $("[type='submit']").click();
        $("samp[for='from_name_as']").shouldBe(Condition.hidden);
    }```

**Comment by vinogradoff** [comment] 2017-03-29 13:01
and without 

PhantomJsDriverManager.getInstance().setup();?

This line should not be necessary.

**Comment by SergeyPirogov** [comment] 2017-03-29 13:19
With version 4.3 everything is ok for me. With 4.4.1 fail

**Comment by asolntsev** [comment] 2017-04-09 09:44
@SergeyPirogov Can you share the whole project? I cannot reproduce the problem.
I guess you are using an old version of `selenium-remote-driver.jar`. In selenium 3.3.1, class `ExecutableFinder` is public.

**Comment by SergeyPirogov** [comment] 2017-04-09 17:09
Well probably you can say why gradle downgrades version of selenium? I added Selenide 4.4.1 and performed. gradlew dependecies and it says that I have

selenium-*.3.3.1 -> 2.53.1 

It's strange. I should explicitly declare selenium-*.3.31 in my build.gradle file. Have newer faced this before

**Comment by asolntsev** [comment] 2017-04-09 21:03
@SergeyPirogov I cannot reproduce the problems. Works fine for me. Can you share your `build.gradle`?

**Comment by uguy** [comment] 2017-04-24 16:17
Hi there,
Same for me with maven, if I add selenium-java 3.3.1 as the unique selenium dep, it pulls the following versions: 

org.seleniumhq.selenium:htmlunit-driver:jar:2.21:compile
org.seleniumhq.selenium:selenium-api:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-chrome-driver:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-edge-driver:jar:3.3.1:compile
org.seleniumhq.selenium:selenium-firefox-driver:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-ie-driver:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-java:jar:3.3.1:compile
org.seleniumhq.selenium:selenium-opera-driver:jar:3.3.1:compile
org.seleniumhq.selenium:selenium-remote-driver:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-safari-driver:jar:2.53.1:compile

Same with version 3.4.0

org.seleniumhq.selenium:htmlunit-driver:jar:2.21:compile
org.seleniumhq.selenium:selenium-api:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-chrome-driver:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-edge-driver:jar:3.4.0:compile
org.seleniumhq.selenium:selenium-firefox-driver:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-ie-driver:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-java:jar:3.4.0:compile
org.seleniumhq.selenium:selenium-opera-driver:jar:3.4.0:compile
org.seleniumhq.selenium:selenium-remote-driver:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-safari-driver:jar:2.53.1:compile
org.seleniumhq.selenium:selenium-support:jar:2.53.1:compile

**Comment by uguy** [comment] 2017-04-24 16:23
Fixed for my case.
My project is a spring-boot one with spring-boot as parent pom which fix selenium version under property selenium.version to <selenium.version>2.53.1</selenium.version>
Overriding the correct property fix the version mess... (in my pom <selenium.version>3.4.0</selenium.version>)
HTH

**Comment by asolntsev** [comment] 2017-04-24 19:40
@uguy Thank you for sharing!
@SergeyPirogov Can we close the issue?

**Closed by asolntsev** 2017-04-24 19:40 UTC
Labels: cannot preproduce

**Comment by beatjost** [comment] 2017-05-09 09:50
Think I have the same/similar issue...
(`java.lang.IllegalAccessError: tried to access class org.openqa.selenium.os.ExecutableFinder from class org.openqa.selenium.phantomjs.PhantomJSDriverService`)

How can I modify my gradle build script to fix this?
Actually used versions:
```
	compile 'org.seleniumhq.selenium:selenium-java:3.4.0'
	testCompile 'org.jmockit:jmockit:1.26'
	testCompile 'org.springframework.boot:spring-boot-starter-test'
	testCompile 'com.codeborne:selenide:4.4.3'

```
thx
