### ISSUE TITLE
Selenide doesn't close browsers on successful run when using a custom WebDriver

### ISSUE THREAD

**Issue by davidhatten** [codeborne/selenide#228] opened 2015-10-05 17:40 UTC
I looked at the code and it looks like adding a new WebDriver doesn't call "markForAutoClose" and I can't find any obvious way of getting selenide to invoke it when given a new WebDriver.

Is it by design that this method isn't called on provided WebDrivers? Is there any way I can force it to register the webdriver for notification after the fact?

**Comment by asolntsev** [comment] 2015-10-05 21:36
@davidhatten It seems to be a bug. I am pretty sure that Selenide should close the webdriver. 

The rule of thumb is pretty simple: the who opens browser should close it. 
In this case, Selenide opens a browser (using provider), so Selenide should also close it.

**Comment by davidhatten** [comment] 2015-10-05 21:55
Right, I figured Selenide should automatically clean it up but I don't know what's in other peoples heads :)

I just got home and reproduced the bug on my machine here, so it's platform agnostic.

My configuration is a Cucumber test calling out a java file which sets up and runs the WebDriver and all the selenide queries. At work the configuration is essentially the same, but far larger.

Here's the project with the reproducing code. You can find all the Cucumber stuff under `src/test` Notice the @After method to close the WebDriver in `DummySteps.java`

https://github.com/xDD-CLE/katas/tree/master/ui_calculator/davidhatten/uicalculator

**Comment by asolntsev** [comment] 2015-10-05 22:02
Wow! Thank you for the sample project.
It will also useful for me to learn Cucumber :)

I will try to reproduce the issue and fix it in next Selenide version.

Andrei Solntsev

2015-10-06 0:55 GMT+03:00 davidhatten <notifications@github.com>:

**Comment by davidhatten** [comment] 2015-10-05 22:11
No problem! It's just a Spring Boot application, so you should be able to pop it in to your IDE, right click `UiCalculatorApplication.java` and select "run" and you should get a run configuration that starts the webapp. Then you can do the same thing to execute the Cucumber feature files, but you might need a Cucumber plugin for your IDE for that to work.

Thanks for the swift attention!

**Comment by davidhatten** [comment] 2015-10-06 13:38
Oh, related, but I don't think Selenide takes a screenshot on failures with a user-provided WebDriver. I think that's because it's not adding the listeners as well as marking it for Auto Close.

**Comment by asolntsev** [comment] 2015-12-21 23:31
@davidhatten Sorry for the long delay.
First if all, what do you mean when saying "custom WebDriver"?

There are two options for setting custom webdriver to Selenide.

### option 1: implementing `WebDriverProvider`
I tried to reproduce this problem with latest Selenide 2.25, and could not. It seems that the problem has been fixed meanwhile. I also made sure that Selenide does take a screenshot with user-provided WebDriver.

### option 2: using method `WebDriverRunner.setWebDriver`
In this case, Selenide should not close the browser. It's by design. As I said earlier, the rule is simple: the one who opens browser should close it.

**Comment by asolntsev** [comment] 2016-01-07 00:02
@davidhatten
I guess we can close the issue.
Please reopen and comment if you are not agree.

**Closed by asolntsev** 2016-01-07 00:02 UTC
Labels: not a bug

**Comment by davidhatten** [comment] 2016-01-07 00:05
Sorry, Totally forgot to respond to this. Thank you for your responsiveness; we ended up making it a goal to ditch Selenium entirely. I love this project though, and I'm going to remember it any time I have to use Selenium in the future. Thanks a lot!

**Comment by asolntsev** [comment] 2016-01-07 00:13
ok, not a problem. Feel free to try Selenide in another project :)

**Comment by bogdanpoli** [comment] 2016-10-10 21:36
close() works for me
