### ISSUE TITLE
timeout and collectionsTimeout should not be affected by implicitlyWait

### ISSUE THREAD

**Issue by abondarev-sel** [codeborne/selenide#534] opened 2017-05-17 09:34 UTC
Hello,
I have a question:

I am using a lot of error verifications after each step. Usually there are less than 10 errors (sometimes they are expected, sometimes - not). Verification is executed in the slowest way, when there are no errors on a page. 

Due to this situation I have adjusted collections timeout, which did not help. My expectation is that errors will be collected in `Configuration.collectionsTimeout` and that `$$(By.xpath("//li[@class='alert']/div[@class='msg-error']")).filter(visible).shouldHave(size(0));` will execute in period of time that is close to collectionsTimeout. Unfortunatelly timeout does not help. Are there other parameters, that I need to adjust? Or is this some kind of an issue?

Here is an example:
```java
// Some actions and then the following 2 steps
@Step("Wait page to load")
    public void waitPageToLoad(){
        if (isDriverJSExecutor()) {
            this.wait.until
                    (new ExpectedCondition<Boolean>() {
                        public Boolean apply(WebDriver driver) {
                            return ((JavascriptExecutor) driver).executeScript("return document.readyState").equals("complete");
                        }
                    });
        }
    }
@Step("Verify that error messages are not shown")
    private void verifyNoErrorMessagesAreShown() throws UIAssertionError, RuntimeException{
        long start = System.nanoTime();
        $$(By.xpath("//li[@class='alert']/div[@class='msg-error']")).filter(visible).shouldHave(size(0));
        long finish = System.nanoTime();
        long timeConsumedMillis = (finish - start) / 1000000;
        System.out.println("Spent: " + timeConsumedMillis);
        System.out.println("Error message timeout should be: " + Configuration.collectionsTimeout);
        System.out.println("Polling interval is: " + Configuration.collectionsPollingInterval);
    }
```

Some outputs are like this:
`Spent: 80
Error message timeout should be: 100
Polling interval is: 2`
Unfortunatelly others are:
`Spent: 2043
Error message timeout should be: 100
Polling interval is: 2`, which is 1900+ milliseconds more than expected

My goal is to reduce time spent for this step - `$$(<elements>).filter(visible).shouldHave(size(0));`

**Comment by abondarev-sel** [comment] 2017-05-17 10:01
Sometimes there is 1 hidden message that has the same xPath. Could `.filter(visible)` slow down this verification because of this hidden message?

**Comment by abondarev-sel** [comment] 2017-05-18 16:43
I have also tried the following approach:
```java
@Step("Check fast that locator exists")
    private boolean locatorExistsCheckFast(By locator){
        boolean locatorExists = true;
        try{ $(locator).waitUntil(exist, 100); }
        catch (ElementNotFound enf) { locatorExists = false; }
        return locatorExists;
    }
```
Unfortunatelly it did not help. I will try to experiment with `Configuration.pageLoadStrategy`

**Comment by abondarev-sel** [comment] 2017-05-22 15:11
I have tried `Configuration.pageLoadStrategy = "none"`. it improved tests performance. Unfortunatelly it did not help with `$(locator).waitUntil(exist, 100);`
I have also tried rining it on Selenium 2.53.1 + Selenide 4.0 and selenium 3.4.0 + Selenide 4.4.3.
In both situations waitUntil sometimes waits just few milliseconds and sometimes up to 3.5 seconds.
I am out of ideas at this point.

**Comment by abondarev-sel** [comment] 2017-05-24 15:34
I have made one run with `locatorExistsCheckFast` and second, when `$(locator).exists();` was used instead (100+ tests with 10+ `exists()` verifications each).
First run took 3h 2m and second 4h 42m. This difference is huge. But I still cannot make `locatorExistsCheckFast` to run in given interval (100). Sometimes it runs 3 seconds or more. Please suggest, what could be improved. 
P.S. I am using Firefox 46 with Selenium 2.53.1 and Selenide 4.0 on Ubuntu 12. There is a plan to move to newer Selenium and Selenide, but it will take some time. I will update this thread, when other OSes will be adjusted.

**Comment by abondarev-sel** [comment] 2017-05-30 14:40
Issue was located. Some legacy tests were updating `implicitlyWait` on the go. Adding 
```java
driver.manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);
``` 
fixed the problem. 
I think this is a bug, as `Configuration.timeout` and `Configuration.collectionsTimeout` should be responsible for selenide elements, bit not `implicitlyWait`.

**Comment by asolntsev** [comment] 2017-05-30 20:59
@abondarev-sel Thank you for sharing results of your investigation!

Do I correctly understand that it was a bug in your tests? And there is nothing to fix in Selenide?
Then can we close the issue?

**Comment by abondarev-sel** [comment] 2017-05-31 07:46
Hello @asolntsev. I think there are 2 points that need to be analyzed and one of them should be applied before closing this issue:

1. This is a Selenide bug, because I did not expect Selenide to be affected by implicit waits. From my understanding Selenide should throw `ElementNotFound` after `timeout` and `collectionsTimeout`. But it actualy waits `implicitlyWait timeout + selenide timeouts`.
**OR**
2. `ElementNotFound` should be thrown after `implicitlyWait timeout + selenide timeouts`. In this case please update Selenide wiki and\or Selenide Java Doc and put information that Selenide Configuration timeouts are summed with Selenium timeouts.

**Comment by asolntsev** [comment] 2017-06-06 22:15
@abondarev-sel The problem is that Selenide cannot check if user has set some implicit timeout. Webdriver API just doesn't have method to ask implicit timeout. 

That's why Selenide cannot know if there is implicit timeout. So, what can we do with that? 
We can only say: "Guys, please don't use implicit timeouts with Selenide" in documentation. :(

**Comment by abondarev-sel** [comment] 2017-06-07 08:39
In this case I think that adding the following or simmilar text [here](http://selenide.org/documentation.html) and\or in Java doc should be enough:

> timeout - waiting timeout in milliseconds, that is used in explicit (should/shouldNot/waitUntil/waitWhile) and implicit waiting for SelenideElement; set to 4000 ms by default; can be changed for specific tests, e.g. Configuration.timeout = 6000. **_This timeout is summed with Selenium timeouts_**;
collectionsTimeout - waiting timeout in milliseconds, that is used in explicit (should/shouldNot/waitUntil/waitWhile) and implicit waiting for ElementsCollection; set to 6000 ms by default; can be changed for specific tests, e.g. Configuration.collectionsTimeout = 8000. **_This timeout is summed with Selenium timeouts_**;

**Comment by asolntsev** [comment] 2017-10-12 20:56
@abondarev-sel It's not exactly correct. This is not always summed. If implicit wait is 2000 and Selenide timeout is 4000, then method `$('#unknown').shouldBe(visible);` will work 4000 ms.

**Comment by abondarev-sel** [comment] 2017-10-13 06:51
@asolntsev yhank you, I will take that to account in future. I have already removed legacy implicit waits from tests, but this may come in handy for others.

**Comment by rosolko** [comment] 2018-05-09 17:27
Looks like issue resolved. If some one face issue like that let's create a new one and work with up to date code base.

**Closed by rosolko** 2018-05-09 17:27 UTC
Labels: question
