### ISSUE TITLE
Feature request: waitUntil(condition, timeout) for ElementCollections

### ISSUE THREAD

**Issue by vinogradoff** [codeborne/selenide#476] opened 2017-02-16 22:57 UTC
Should have method $$().waitUntil(collectionCondition, timeout) which allows to set timeout for a single action.

**Comment by asolntsev** [comment] 2018-08-20 20:32
Duplicate of https://github.com/codeborne/selenide/issues/601
Was released in Selenide 4.13.0

**Closed by asolntsev** 2018-08-20 20:32 UTC
Labels: duplicate, feature
