### ISSUE TITLE
Selenide is not taking screenshot on failure - Related to Issue #180

### ISSUE THREAD

**Issue by leslyarun** [codeborne/selenide#182] opened 2015-05-18 10:58 UTC
After fixing issue #180 , selenide is not taking screenshot on failure.

Please find below a sample stacktrace:

Running TestSuite
Started InternetExplorerDriver server (32-bit)
2.45.0.0
Listening on port 36195

 === CLOSE WEBDRIVER: 1 -> InternetExplorerDriver: internet explorer on WINDOWS (07dde8c8-b03c-4ffe-b606-18cd6b85c510)

Cannot take screenshot because browser is not started

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 85.3 sec <<< FAILURE! - in TestSuite
searchTest(com.Schedule.ScheduleTest)  Time elapsed: 46.023 sec  <<< FAILURE!
com.codeborne.selenide.ex.ElementNotFound: Element not found {By.xpath: /html/body/div[1]/section/div/div[7]/div/div[1]/div/div[3]/div[1]}
Expected: visible
	at sun.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:357)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:28)
	at com.codeborne.selenide.impl.WaitingSelenideElement.getActualDelegate(WaitingSelenideElement.java:55)
	at com.codeborne.selenide.impl.AbstractSelenideElement.checkCondition(AbstractSelenideElement.java:477)
	at com.codeborne.selenide.impl.AbstractSelenideElement.should(AbstractSelenideElement.java:466)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invokeShould(AbstractSelenideElement.java:298)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchSelenideMethod(AbstractSelenideElement.java:178)
	at com.codeborne.selenide.impl.AbstractSelenideElement.dispatchAndRetry(AbstractSelenideElement.java:94)
	at com.codeborne.selenide.impl.AbstractSelenideElement.invoke(AbstractSelenideElement.java:65)
	at com.codeborne.selenide.impl.WaitingSelenideElement.invoke(WaitingSelenideElement.java:18)
	at com.sun.proxy.$Proxy6.waitUntil(Unknown Source)
	at com.hoegh.testcases.Schedule.ScheduleTest.searchTest(ScheduleTest.java:41)

Results :

Failed tests: 
  ScheduleTest.searchTest:41 Element not found {By.xpath: /html/body/div[1]/section/div/div[7]/div/div[1]/div/div[3]/div[1]}
Expected: visible

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0

**Comment by asolntsev** [comment] 2015-05-18 21:16
It seems that you have not started browser.
You see an error message in your stack trace: `Cannot take screenshot because browser is not started`

In my tests, Selenide 2.18.1 does take screenshots.

**Comment by leslyarun** [comment] 2015-05-19 05:31
I didn't close the browser.
Browser was closed automatically, as you can see - **=== CLOSE WEBDRIVER: 1 -> InternetExplorerDriver: internet explorer on WINDOWS (07dde8c8-b03c-4ffe-b606-18cd6b85c510)** appears first and only after browser got closed, selenide tried to take screenshot

**Comment by leslyarun** [comment] 2015-05-20 09:33
@asolntsev  Any Update on this issue ?

**Comment by asolntsev** [comment] 2015-05-20 10:52
Sorry, not yet. Will analyze it soon.

**Comment by asolntsev** [comment] 2015-05-21 17:11
Well, I reproduced the problem few times in my work project today. Seems that it's a kind of timing issue, the error happens randomly.Continueing investigation...

**Comment by asolntsev** [comment] 2015-05-24 12:03
Catched the problem. The solution will be released in few hours as Selenide 2.18.2

**Comment by asolntsev** [comment] 2015-05-24 14:00
@leslyarun released selenide 2.18.2!

**Closed by asolntsev** 2015-05-24 14:00 UTC
Labels: ready

**Comment by leslyarun** [comment] 2015-05-25 02:31
@asolntsev Thanks a lot :)

**Comment by leslyarun** [comment] 2015-05-25 11:38
@asolntsev Have u released Selenide 2.18.2 ???
I end up with errors when i add version 2.18.2 in maven
 <dependency>
    <groupId>com.codeborne</groupId>
    <artifactId>selenide</artifactId>
    <version>2.18.2</version>
    <scope>test</scope>
</dependency>

**Comment by asolntsev** [comment] 2015-05-25 11:41
Yes, selenide 2.18.2 has been released yesterday.
Here it is:
http://search.maven.org/#artifactdetails%7Ccom.codeborne%7Cselenide%7C2.18.2%7Cjar

And it's pom:
https://repo1.maven.org/maven2/com/codeborne/selenide/2.18.2/selenide-2.18.2.pom

And it's jar:
http://search.maven.org/remotecontent?filepath=com/codeborne/selenide/2.18.2/selenide-2.18.2.jar


Andrei Solntsev

2015-05-25 14:38 GMT+03:00 leslyarun <notifications@github.com>:

**Comment by leslyarun** [comment] 2015-05-25 11:48
@asolntsev I'm getting errors if I use 2.18.2 ???

**Comment by asolntsev** [comment] 2015-05-25 13:28
@leslyarun What errors? Can you provide stack trace or at least error message?

**Comment by leslyarun** [comment] 2015-05-26 06:42
@asolntsev if i change the version to 2.18.2 in pom.xml , I get error in pom.xml saying - **ArtifactDescriptorException: Failed to read artifact descriptor for com.codeborn (Click for 54 more) **

**Comment by asolntsev** [comment] 2015-05-26 08:08
It seems like some Mavens problem.
Ivy and Gradle can resolve Selenide 2.18.2

Probably you are using some proxy server for maven?

Sent from my HTC

----- Reply message -----

**Comment by leslyarun** [comment] 2015-05-26 08:59
ya im using proxy server. 
Any workarounds for this ?

**Comment by leslyarun** [comment] 2015-05-26 09:50
@asolntsev Hey buddy, found that it was a proxy issue. Fixed it.
Thanks a lot for ur assistance :+1:

**Comment by BadNews87** [comment] 2015-05-26 15:50
What was the problem, I'm also a Maven user so I'd like to know how to avoid issues.

**Comment by leslyarun** [comment] 2015-05-27 06:51
@BadNews87 Well actually it wasn't a Maven issue. 
I recently changed my proxy settings, but I forgot to update that in settings.xml file

**Comment by BadNews87** [comment] 2015-05-27 06:53
Thanks for the quick answer. It seems I'm good to go with the update.

**Comment by BadNews87** [comment] 2015-05-27 06:56
Thanks for the quick answer. Seems I'm good to go with my update.

**Comment by BadNews87** [comment] 2015-05-27 07:17
The screenshot issue was so mixed up that Selenide was making screenshots for each tests instead of only the ones with error. It's good to know that now everything is ok with that. I had multiple png's save on my drive which were very painful to delete.
