### ISSUE TITLE
Remove deprecated APIs

### ISSUE THREAD

**Issue by asolntsev** [codeborne/selenide#806] opened 2018-09-19 21:09 UTC
In upcoming major release Selenide 5.0.0, we want to delete deprecated and unused functionality from Selenide. We need to know your opinion. Please say in comments if you use some of settings/functions below. 

I suggest to delete the following settings:
- [x] `Configuraton.collectionsTimeout`  (let it be same as `Configuraton.timeout`).
- [x] `Configuration.collectionsPollingInterval` (let it be same as `Configuration.pollingInterval`).
- [x] `Configiration.closeBrowserTimeoutMs` (browser is closed anyway in a separate daemon thread).
- [x] `Configuration.chromeSwitches` (it has been deprecated for a while)
- [x] `Configuration.captureJavascriptErrors`  (it doesn't work well anyway) - remove `JavascriptErrorsCollector` as well
- [x] `Configuration.setValueChangeEvent` (we introduced this setting just in case to avoid breaking changes. Now it's clear for me that it's not needed).

I also suggest to delete the following deprecated `Condition`s:
- [x] `present`
- [x] `hasAttribute`
- [x] `hasValue`
- [x] `hasText`
- [x] `hasClass`

**UPD**.  @eichisanden @Vyachelav @SergeyPirogov 
The community voted that these two features should **not be removed** because people do actually use them:
1. `Configuration.assertionMode` (it seems to me that soft assertion is not really useful in Selenide, and nobody actually uses it).
2. `Configuration.holdBrowserOpen` (it's only needed during local debug - but you can debug without a setting anyway)

**Comment by cocorossello** [comment] 2018-09-19 22:55
We use collectionsTimeout and collectionsPollingInterval, but it's better to leave as you say. I just changed the deprecated present and we don't use any more settings. Seems reasonable.

**Comment by eichisanden** [comment] 2018-09-20 03:53
Please do not delete `Configuration.holdBrowserOpen`.  
Because I want to use Chrome Devtools to investigate the cause of error during debugging.  
Since it can not be investigated if the browser is closed.

**Comment by aleksandr-kotlyar** [comment] 2018-09-20 06:26
```hasAttribute
hasValue
hasText
hasClass```
Ok, but i hope that `has(Condition)` will remain. Will it?

**Comment by asolntsev** [comment] 2018-09-20 06:33
Yes, `has(Condition)` will remain. Thought, I still don't recommend to use these `is`/`has` methods that return boolean. It's a bad practice to put  IFs in your tests.

**Comment by asolntsev** [comment] 2018-09-20 06:37
@eichisanden It seems to be the most popular. Let's move discussion to the separate issue: https://github.com/codeborne/selenide/issues/807

Please answer there, why the standard error message with screenshot and html is not enough.

**Comment by Vyachelav** [comment] 2018-09-20 08:34
Please, won't delete Configuration.assertionMode, my colleagues and I use SoftAssertions, it's really useful and more comfortable to use it for us. More comfortable than testng soft asserts.

**Comment by BorisOsipov** [comment] 2018-09-23 09:08
What about this?
https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/WebDriverRunner.java#L23

I think we can remove it. It is easy to fix if someone still use this.

**Comment by asolntsev** [comment] 2018-09-25 06:49
@BorisOsipov You mean method `addListener()`? I guess people use it - for example, for logging.
I use it myself in the Gmail example: https://github.com/selenide-examples/gmail/blob/master/test/org/selenide/examples/gmail/GmailTests.java

**Comment by BorisOsipov** [comment] 2018-09-25 07:05
@asolntsev 	nope, about this alias for IE https://github.com/codeborne/selenide/blob/a8b19f9c849ec9fa07ad9cab6dbb2080d1d7d08d/src/main/java/com/codeborne/selenide/Browsers.java#L13

**Comment by SergeyPirogov** [comment] 2018-09-25 07:10
Listener is also used for allure integration with Selenide

 SelenideLogger.addListener("AllureSelenide", new AllureSelenide());

**Comment by rosolko** [comment] 2018-09-25 07:13
@SergeyPirogov No plan to remove listeners. We just investigate if it's possible to remove `IE` alias and leave only `InternetExplorer`

**Comment by asolntsev** [comment] 2018-09-25 15:27
@rosolko @BorisOsipov Now it's easy to run tests with ie: `-Dselenide.browser=ie`.
If we remove this constant, it will be a bit harder: `-Dselenide.browser="internet explorer";`. Million of problems with commas and spaces guaranteed. Is this constant really so bad?

**Comment by rosolko** [comment] 2018-09-25 16:05
@asolntsev This constant marked as deprecated. So we need to decide if really need it and sd result keep it or remove.

**Comment by aleksandr-kotlyar** [comment] 2018-09-25 17:55
@asolntsev , i think `"ie"` is useful in your case. Please, unmark it as deprecated. One row is not huge, it's useful more important.

**Comment by BorisOsipov** [comment] 2018-09-25 17:56
>Now it's easy to run tests with ie: -Dselenide.browser=ie.

Agree

**Comment by rosolko** [comment] 2018-09-27 20:09
Remove only `closeBrowserTimeoutMs`configuration.
Move value directly to `CloseDriverCommand` ctor.

**Closed** 2018-09-30 10:55 UTC
