### ISSUE TITLE
Add .because to comparison with numbers

### ISSUE THREAD

**Issue by sergitorralba** [codeborne/selenide#728] opened 2018-05-04 15:17 UTC
## The problem
Impossible to add a because reason to a "sizeGreaterThan" comparison

## Details
I was trying to have a clearer report and the because option appears on the text option but not in the number comparison 

## Tell us about your environment
* **Selenide Version:Selenide v. 4.11.2**

## Code To Reproduce Issue [ Good To Have ]
results.getResults().shouldHave(sizeGreaterThan(1).because("I really want to compare it with 1");

**Comment by BorisOsipov** [comment] 2018-05-05 18:11
duplicate of https://github.com/codeborne/selenide/issues/440

**Closed by BorisOsipov** 2018-05-05 18:11 UTC
