### ISSUE TITLE
Different test outcome depend on browser - selenide selenium

### ISSUE THREAD

**Issue by hana9090** [codeborne/selenide#313] opened 2016-04-13 10:41 UTC
I have number of tests in the juint test class, By using maven environment with Selenide version 3.5.1.
for these tests, browser wil be only opened for the first test and closed at the last test.

I tried to run them using chrome & firefox browsers:
1. Chrome: all test are run successfully
2. Firefox: there are some tests are failed, and I feel it was randomly failed.

For each test, I need to click on button where a pop-box will appear.
- for chrome: each test the pop-box appeared when the button was clicked
- for firefox: randomly the pop-box didn't appear when the button was clicked.

I don't know what is the problem reason!

**Comment by vinogradoff** [comment] 2016-04-13 11:40
It is too general, what help do you expect with this level of details?

Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by hana9090** [comment] 2016-04-13 11:47
okay, I am just want to make login to by make different tests with different username and password.

           ``` @Test
	    public void Test1() {
		browser= System.getProperty("browser");
		if(browser ==null)
			browser="firefox";
		if(Objects.equals(browser,"chrome"))
		{
			System.setProperty("webdriver.chrome.driver", "Resources/chromedriver.exe");
			WebDriverRunner.setWebDriver(new ChromeDriver()); 
		}
		
		System.out.println("--------------> > using "+ browser +" browser");
		String url="http://vanilla.sa/";
		
		 WebDriverRunner.clearBrowserCache();
		
		open(url);
		
		//click on Login
		$("body.page-common_home  div.navbar.navbar-default.navbar-fixed-top.hidden-xs div.container div.navbar-collapse.collapse ul.nav.navbar-nav.categories-links li.jsUserLoginUrl a").click();
		
		//the login form should be appeared 
		$(".modal-dialog").shouldBe(visible);
		
		//enter the email and the password
		$(By.name("email")).val("email1");
		$(By.name("password")).val("pass2").pressEnter(); 
		
		//the login form should be disappeared 
		$(By.className("alert-danger")).shouldNotBe(visible);		
		
	}
```


there are other three tests Test2, Test3, Test4. all of them same code except field values

**Comment by dmlemeshko** [comment] 2016-04-13 12:02
Friendly suggestion: Start with definition of test design and execution.
1)Why do you use `WebDriverRunner.setWebDriver` if you do not provide any custom driver?
Just set system property in `pom.xml` and simply use `open`
2) If you decided to go with `WebDriverRunner.setWebDriver`, then you handle closing your custom-but-not-really driver at the end of each test (at least it was actual for selenide v2.x). 
3) Try to use BeforeTest/AfterTest annotations to simplify your code.
4) Stacktrace required to understand your issue

**Comment by vinogradoff** [comment] 2016-04-13 12:48
You may try setting Configuration.fastSetValue=true;


Viele Grüße
Alexei Vinogradov 
--
Sent from mobile phone

**Comment by hana9090** [comment] 2016-04-14 10:52
Thanks @dmlemeshko  for suggestion but the code is so simple and I noticed the same problem occurred just becuase use firefox instead of chrome

**Comment by hana9090** [comment] 2016-04-14 10:53
@vinogradoff  I inserted it before test run, but same problem occurred :\ 
```
@Before
	public void testSetUp()
{
Configuration.fastSetValue=true;
}
```

**Comment by hana9090** [comment] 2016-04-14 11:20
I tried to add this statemnt instead of     `$(".modal-dialog").shouldBe(visible);`

```
WebDriverWait waitLog = new WebDriverWait(WebDriverRunner.getWebDriver(), 2);             
waitLog.until(ExpectedConditions.elementToBeClickable($(".modal-dialog")));
```

but still the tests are failed, the pop window can't wait to enter username and password, it disappeared before filling fields!

**Comment by hana9090** [comment] 2016-04-14 11:51
My notes:

   

-  for chrome browser (v2.9.24) , all tests have successful run.

    

- when I used the latest firefox browser(v45.0.1), only first test has a successful run and others are failed.

   

-  some of them can't catch the pop-window to enter values, and then it will continue for the next test.

  

-   In some cases, pop-window can't wait, it disappeared quickly and then unit test can't find username and password fields to fill values.


I need to test them on firefox, so how to overcome this problem.

**Comment by dmlemeshko** [comment] 2016-04-14 14:11
@hana9090 , I don't think that you can expect element to be clickable within 2 sec, if it previously failed to become visible within 4 sec (default Selenide timeout). Please check `WebDriverWait` java doc: https://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/support/ui/WebDriverWait.html
Btw did you try Selenide method `waitUntil(Condition condition, long timeoutMs)` ?
Probably your element `.modal-dialog` does not become visible within `4 sec' in specific browser for a constant time.
Maybe `$(".modal-dialog").waitUntil(visible, 10000)` will work?

Regards, Dmitry

**Comment by hana9090** [comment] 2016-04-14 17:43
@dmlemeshko 
Thanks for your suggestion.
I tried this  `$(".modal-dialog").waitUntil(visible, 10000)`, but the same problem happened tests are unable to catch fields of `modal-dialog` or can't catch the pop-window(modal-dialog) itself.

**Comment by hana9090** [comment] 2016-04-15 07:07
@dmlemeshko , @vinogradoff 

for each test, if I open and close the web driver, the tests have a successful run. 

```
Test(){
open(url);
//Test code
WebDriverRunner.closeWebDriver();
}
```

but if each test I didn't close the driver, the test will be failed.

Any idea?

**Comment by dmlemeshko** [comment] 2016-04-15 08:18
@hana9090,
As I already mentioned, if you provide your custom driver to Selenide via `WebDriverRunner.setWebDriver`, then it is your responsibility to close it. This is per design, you must handle driver sessions. But since you simple provide `new ChromeDriver()` to Selenide, it doesn't make sense at all to do it this way.
You still did not provide any stacktrace for failed tests, so it is difficult to guess the root cause.

**Comment by hana9090** [comment] 2016-04-15 08:24
I know that Selenide handle driver open and close, when I used default Seleinde driver (firefox), I got this problem, when I run each test in a different Juint test, then test has a successful run, but problem appear when I have a number of test within same juint test.

for error stack, different behaviour occurred, sometimes it can't see dialog or can't have time enough to fill its field before go to the next test.

**Comment by thasherwin** [comment] 2016-04-15 10:28
@hana9090 
Can you please share the error log you get once a fireofx test fails?

**Comment by hana9090** [comment] 2016-04-15 11:58
all tests have same code manner, like following:

```
@Test
public void Test() {		
	String url="http://vanilla.sa/";
	WebDriverRunner.clearBrowserCache();
	open(url);
	
	//click on Login
	$("body.page-common_home  div.navbar.navbar-default.navbar-fixed-top.hidden-xs div.container div.navbar-collapse.collapse ul.nav.navbar-nav.categories-links li.jsUserLoginUrl a").click();
	WebDriverWait wait = new WebDriverWait(WebDriverRunner.getWebDriver(), 10);
	WebElement dialog= wait.until(ExpectedConditions.visibilityOfElementLocated(By.className("modal-dialog")));
	
	WebElement email = wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("email")));
	WebElement password = wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("password")));
	//enter the email 
	$(By.name("email")).val("@"); //then press enter
	$(By.name("password")).val("*");

	WebDriverRunner.getWebDriver().manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
	$(By.name("email")).pressEnter(); 

	$(By.className("alert-danger")).shouldBe(visible)
	    	.shouldBe(text("لا يوجد تطابق مع البريد الإلكتروني / كلمة المرور."));
	
	}
```

problems happen before checking the test condition to check (`alert-danger`), and as said before this happened because I used firfox and different tests within same Juint test class.

error stack: 

The first test has a successful run but the second one has this error::
- 

> eElement should be visible {By.name: email}
> Element: '< input class="form-control" name="email" placeholder="البريد الإلكتروني" type="text" displayed:false ></ input>'

The third test has the following error:
- 

> eTimed out after 10 seconds waiting for visibility of element located by By.className: modal-dialog

**Comment by thasherwin** [comment] 2016-04-16 06:39
@hana9090
I do see problems that occurs on FF sometimes but not on chrome. My workaround are to click on an element using javascript or connect an old selenium node jar
 to a grid. I use 2.45 jar version as node for testing on Firefox. I noticed that clicking not always work with the latest Selenium version on Firefox. Not sure if this is the best solution. Maybe someone else have a better suggestion.

**Comment by asolntsev** [comment] 2016-05-09 22:48
@hana9090

Please simplify your tests. They are just too complex. 
And please, **do not use implicit wait** in your tests with Selenide.

Look, this is your test, but simplified. It works both in Firefox and Chrome:

```java
public class LoginTest {
  String url="http://vanilla.sa/";

  @Before
  public void setUp() {
    Configuration.browser = "firefox";
    WebDriverRunner.clearBrowserCache();
  }

  @Test
  public void validateEmailAtLogin() {
    open(url);

    //click on Login
    $("body.page-common_home  div.navbar.navbar-default.navbar-fixed-top.hidden-xs div.container div.navbar-collapse.collapse ul.nav.navbar-nav.categories-links li.jsUserLoginUrl a").click();

    $(".modal-dialog").find(By.name("email")).val("@");
    $(".modal-dialog").find(By.name("password")).val("*");
    $(".modal-dialog").find(By.name("email")).pressEnter();

    $(".alert-danger")
        .shouldBe(visible)
        .shouldHave(text("لا يوجد تطابق مع البريد الإلكتروني / كلمة المرور."));
  }
}
```

**Comment by asolntsev** [comment] 2016-12-10 23:14
It seems no feedback here. Closing the issue.

**Closed by asolntsev** 2016-12-10 23:14 UTC
Labels: cannot preproduce, question
