### ISSUE TITLE
ElementCollection.isEmpty() doesn't return correct value

### ISSUE THREAD

**Issue by hanushs** [codeborne/selenide#650] opened 2017-12-22 19:50 UTC
Hello
I'm using Classic POM and using

@FindBy(css = ".busy-indicator-message")
 public ElementsCollection busyIndicator;

In process when i'm trying to get method isEmpty() return value for ElementCollection it is always shows true, even though element disappears in process!!

When i use $$(".busy-indicator-message").isEmpty() it is changes return value from true to false, since loading indicator disappears.

Looks like ElementCollection.isEmpty() keeps the value from it first reference and doesn't do search repeatedly for elements!

Here is output from program test execution:

2017-12-22 14:24:06 BasePage [main] [INFO]**false**  - ElementCollection.isEmpty()
2017-12-22 14:24:06 BasePage [main] [INFO]**false** - $$(".busy-indicator-message").isEmpty()
2017-12-22 14:24:06 BasePage [main] [INFO]Busy indicator is present. Waiting for operation finalization...
2017-12-22 14:24:08 BasePage [main] [INFO]**false** - ElementCollection.isEmpty()
2017-12-22 14:24:08 BasePage [main] [INFO]**true** - $$(".busy-indicator-message").isEmpty()

SUMMARY.Either i don't understand something or it is not working correctly

**Tell us about your environment**

Selenide Version: 4.8
Chrome: 63.0.3239.108 (Official Build) (64-bit)
Browser Driver Version: 2.34
OS Version: Windows 10

**Comment by BorisOsipov** [comment] 2017-12-23 08:17
duplicate of https://github.com/codeborne/selenide/issues/181

See explanation in comment https://github.com/codeborne/selenide/issues/181#issuecomment-111877102

**Closed by BorisOsipov** 2017-12-23 08:17 UTC
